<a href="https://colab.research.google.com/github/shaya-686/AI/blob/main/%D0%94%D0%97_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [1]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [2]:
a = np.arange(30, 71, 2)
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію

In [6]:
a = np.linspace(0, 1, 10, endpoint=False)
print(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [25]:
def extend_matrix(matrix):
  size = matrix.shape[0]
  extended_matrix = np.zeros((size + 2, size + 2), dtype=matrix.dtype)
  extended_matrix[1:size + 1, 1:size + 1] = matrix
  return extended_matrix

matrix = np.random.randint(1, 10, size=(4, 4))
extended_matrix = extend_matrix(matrix)
print("Original matrix:\n",matrix)
print("Extended matrix:\n",extended_matrix)

Original matrix:
 [[5 4 1 5]
 [2 6 5 4]
 [4 1 3 1]
 [9 6 3 8]]
Extended matrix:
 [[0 0 0 0 0 0]
 [0 5 4 1 5 0]
 [0 2 6 5 4 0]
 [0 4 1 3 1 0]
 [0 9 6 3 8 0]
 [0 0 0 0 0 0]]


#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [26]:
print(f"original matrix type = {extended_matrix.dtype}")
extended_matrix = extended_matrix.astype(np.float32)
print(f"new matrix type = {extended_matrix.dtype}")

original matrix type = int64
new matrix type = float32


#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [27]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5
x[x == var] = -1
print(x)
x[x > var] = -1
print(x)
x[x < var] = -1
print(x)

[ 1 -1  3  8  6 -1  7  4]
[ 1 -1  3 -1 -1 -1 -1  4]
[-1 -1 -1 -1 -1 -1 -1 -1]


#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [30]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])
X[np.isnan(X)] = -1
print(X)

[[ 1.  2. -1.  4.]
 [ 5. -1. -1.  4.]
 [-1. 10. 11. -1.]]


#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [38]:
random_matrix = np.random.randint(1, 10 , size=(4, 6))
print("Original matrix:\n", random_matrix)
new_matrix = random_matrix.reshape(3,8)
print("New matrix:\n", new_matrix)

Original matrix:
 [[4 4 7 2 9 7]
 [2 1 4 6 4 5]
 [1 4 9 9 8 7]
 [3 7 9 7 3 1]]
New matrix:
 [[4 4 7 2 9 7 2 1]
 [4 6 4 5 1 4 9 9]
 [8 7 3 7 9 7 3 1]]


#Завдання 9
Створіть матрицю з одиниць розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [37]:
ones_matrix = np.ones((3, 4), dtype = np.int64)
print("Original matrix:\n", ones_matrix)
column_mean = ones_matrix.mean(axis=0)
print("Column mean: ", column_mean)

Original matrix:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Column mean:  [1. 1. 1. 1.]


#Завдання 10
Створіть випадкову матрицю розміром 5х6. Округліть значення до одного знаку після коми(np.round). Розмістіть стовпчики так, щоб значення в першому рядку були відсортовані за зростанням

In [69]:
random_matrix = np.random.randn(5, 6).round(decimals=1)
print("Original matrix: \n", random_matrix)
ind = random_matrix[0].argsort()
print("Indexes: ", ind)
print("Sorted matrix: \n", random_matrix[:,ind])

Original matrix: 
 [[ 0.1  1.2  0.1  0.8  0.4 -0.4]
 [ 0.7  1.8  0.3 -0.2 -0.8 -1.9]
 [-0.1 -0.6 -0.8  0.7  1.4 -1. ]
 [-1.5 -1.1  0.4 -0.7  0.5 -0.3]
 [ 1.   0.7 -0.7 -1.3 -1.3 -1.3]]
Indexes:  [5 0 2 4 3 1]
Sorted matrix: 
 [[-0.4  0.1  0.1  0.4  0.8  1.2]
 [-1.9  0.7  0.3 -0.8 -0.2  1.8]
 [-1.  -0.1 -0.8  1.4  0.7 -0.6]
 [-0.3 -1.5  0.4  0.5 -0.7 -1.1]
 [-1.3  1.  -0.7 -1.3 -1.3  0.7]]


#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [75]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])
X_bool = np.logical_and(X > 3, X < 6)
print("Bool matrix: \n", X_bool)
result_array = X[X_bool]
print("Result array: ", result_array)

Bool matrix: 
 [[False False False  True  True]
 [False False False False False]
 [False False False False  True]
 [ True False False False False]]
Result array:  [4 5 5 4]


#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом цього стовпчика.

Після цього всі значення мають бути в межах [0, 1]

In [82]:
matrix = np.random.randint(1, 10, size = (5, 6))
print("Original matrix:\n", matrix)

min_column = matrix.min(axis = 0, keepdims=True)
min_max_diff = matrix.max(axis = 0, keepdims=True)-matrix.min(axis = 0, keepdims=True)
print("Diff between min and max: ", min_max_diff)

new_matrix = (matrix - min_column)/min_max_diff
print("Normalized matrix: \n", new_matrix.round(decimals=2))

Original matrix:
 [[4 2 5 2 2 1]
 [5 8 3 8 4 9]
 [3 1 3 5 7 8]
 [3 4 7 1 4 1]
 [6 3 6 6 8 4]]
Diff between min and max:  [[3 7 4 7 6 8]]
Normalized matrix: 
 [[0.33 0.14 0.5  0.14 0.   0.  ]
 [0.67 1.   0.   1.   0.33 1.  ]
 [0.   0.   0.   0.57 0.83 0.88]
 [0.   0.43 1.   0.   0.33 0.  ]
 [1.   0.29 0.75 0.71 1.   0.38]]
