<a href="https://colab.research.google.com/github/shaya-686/AI/blob/main/module2/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [1]:
import numpy as np

# Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

In [4]:
a = np.arange(1, 13)
print(a, a.shape, type(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12] (12,) <class 'numpy.ndarray'>


# Завдання 2
Зробіть на основі попереднього масиву матрицю з 4 стовчиками. Змініть тип даних матриці на float32. Виведіть транспоновану матрицю.

In [8]:
b = a.reshape(-1, 4)
print(b)
b = np.array(b, dtype = np.float32)
print(b)
print(b.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]


#Завдання 3
Створіть матрицю 8х8 з 0 та 1 розміщеними в шаховому порядку

In [14]:
a = np.zeros((8,8), dtype = int)
a[::2, ::2] = 1
a[1::2, 1::2] = 1
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# Завдання 4
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

In [20]:
m = np.random.random((4,3))
print(m)
row_sum = np.sum(m, axis=1)
print(row_sum)
column_sum = np.sum(m, axis=0)
print(column_sum)
print(np.sum(m))

[[0.59903856 0.43978164 0.55720347]
 [0.6097184  0.2236755  0.15571564]
 [0.65222951 0.22514933 0.07840579]
 [0.50555374 0.87434664 0.21549008]]
[1.59602367 0.98910954 0.95578463 1.59539046]
[2.3665402  1.76295312 1.00681498]
5.13630830078569


# Завдання 5
У попередній матриці від кожного рядка відніміть максимальний елемент цього рядка

In [26]:
max_row = np.max(m, axis=1, keepdims=True)
print(max_row)
new_m = m - max_row
print(new_m)

[[0.59903856]
 [0.6097184 ]
 [0.65222951]
 [0.87434664]]
[[ 0.         -0.15925692 -0.04183509]
 [ 0.         -0.38604289 -0.45400275]
 [ 0.         -0.42708018 -0.57382372]
 [-0.3687929   0.         -0.65885657]]


# Завдання 6
Є дані про вагу контейнерів для перевезення на кораблі: дрібний - 5 т,  малий - 10 т, середній - 25 т, великий - 40 т. На кораблі розміщено 20 дрібних, 5 малих, 10 середніх та 4 великих контейнерів. Знайти масу вантажу.

# Завдання 7
Тепер у нас декілька кораблів. Напишіть код для обчислення вантажу на кожному кораблі.